// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: battle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleInputOperation int32

const (
	BattleInputOperation_Start        BattleInputOperation = 0 // 开始战斗
	BattleInputOperation_TickEvent    BattleInputOperation = 1 // 游戏tick事件
	BattleInputOperation_UseItem      BattleInputOperation = 2 // 使用道具
	BattleInputOperation_End          BattleInputOperation = 3 // 结束战斗
	BattleInputOperation_Pause        BattleInputOperation = 4 // 暂停战斗
	BattleInputOperation_Resume       BattleInputOperation = 5 // 恢复战斗
	BattleInputOperation_StatusUpdate BattleInputOperation = 6 // 状态更新
	BattleInputOperation_Destroy      BattleInputOperation = 7 // 销毁战斗 (例如清理资源)
)

// Enum value maps for BattleInputOperation.
var (
	BattleInputOperation_name = map[int32]string{
		0: "Start",
		1: "TickEvent",
		2: "UseItem",
		3: "End",
		4: "Pause",
		5: "Resume",
		6: "StatusUpdate",
		7: "Destroy",
	}
	BattleInputOperation_value = map[string]int32{
		"Start":        0,
		"TickEvent":    1,
		"UseItem":      2,
		"End":          3,
		"Pause":        4,
		"Resume":       5,
		"StatusUpdate": 6,
		"Destroy":      7,
	}
)

func (x BattleInputOperation) Enum() *BattleInputOperation {
	p := new(BattleInputOperation)
	*p = x
	return p
}

func (x BattleInputOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleInputOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_proto_enumTypes[0].Descriptor()
}

func (BattleInputOperation) Type() protoreflect.EnumType {
	return &file_battle_proto_enumTypes[0]
}

func (x BattleInputOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleInputOperation.Descriptor instead.
func (BattleInputOperation) EnumDescriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{0}
}

type BattleErrorCode int32

const (
	BattleErrorCode_SUCCESS              BattleErrorCode = 0 // 成功
	BattleErrorCode_INVALID_REQUEST      BattleErrorCode = 1 // 请求格式错误
	BattleErrorCode_TEAM_NOT_FOUND       BattleErrorCode = 2 // 队伍未找到
	BattleErrorCode_INVALID_TEAM_SIZE    BattleErrorCode = 3 // 队伍大小无效
	BattleErrorCode_BATTLE_NOT_FOUND     BattleErrorCode = 4 // 战斗未找到
	BattleErrorCode_DUPLICATE_BATTLE     BattleErrorCode = 5 // 战斗重复
	BattleErrorCode_INTERNAL_ERROR       BattleErrorCode = 6 // 内部错误
	BattleErrorCode_TIMEOUT              BattleErrorCode = 7 // 超时
	BattleErrorCode_INVALID_PROTO_FORMAT BattleErrorCode = 8 // Protobuf 格式错误
)

// Enum value maps for BattleErrorCode.
var (
	BattleErrorCode_name = map[int32]string{
		0: "SUCCESS",
		1: "INVALID_REQUEST",
		2: "TEAM_NOT_FOUND",
		3: "INVALID_TEAM_SIZE",
		4: "BATTLE_NOT_FOUND",
		5: "DUPLICATE_BATTLE",
		6: "INTERNAL_ERROR",
		7: "TIMEOUT",
		8: "INVALID_PROTO_FORMAT",
	}
	BattleErrorCode_value = map[string]int32{
		"SUCCESS":              0,
		"INVALID_REQUEST":      1,
		"TEAM_NOT_FOUND":       2,
		"INVALID_TEAM_SIZE":    3,
		"BATTLE_NOT_FOUND":     4,
		"DUPLICATE_BATTLE":     5,
		"INTERNAL_ERROR":       6,
		"TIMEOUT":              7,
		"INVALID_PROTO_FORMAT": 8,
	}
)

func (x BattleErrorCode) Enum() *BattleErrorCode {
	p := new(BattleErrorCode)
	*p = x
	return p
}

func (x BattleErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_proto_enumTypes[1].Descriptor()
}

func (BattleErrorCode) Type() protoreflect.EnumType {
	return &file_battle_proto_enumTypes[1]
}

func (x BattleErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleErrorCode.Descriptor instead.
func (BattleErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{1}
}

// 战斗通知类型枚举
type NotificationType int32

const (
	NotificationType_STATUS_UPDATE    NotificationType = 0 // 状态更新
	NotificationType_EVENT_OCCURRED   NotificationType = 1 // 事件发生
	NotificationType_BATTLE_COMPLETED NotificationType = 2 // 战斗完成
	NotificationType_ERROR_OCCURRED   NotificationType = 3 // 错误发生
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "STATUS_UPDATE",
		1: "EVENT_OCCURRED",
		2: "BATTLE_COMPLETED",
		3: "ERROR_OCCURRED",
	}
	NotificationType_value = map[string]int32{
		"STATUS_UPDATE":    0,
		"EVENT_OCCURRED":   1,
		"BATTLE_COMPLETED": 2,
		"ERROR_OCCURRED":   3,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_battle_proto_enumTypes[2].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_battle_proto_enumTypes[2]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{2}
}

// 队伍信息
type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lineup        []uint32               `protobuf:"varint,1,rep,packed,name=lineup,proto3" json:"lineup,omitempty"`             // 阵容ID列表
	TeamId        uint32                 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`      // 队伍ID
	TeamName      string                 `protobuf:"bytes,3,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"` // 队伍名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetLineup() []uint32 {
	if x != nil {
		return x.Lineup
	}
	return nil
}

func (x *Team) GetTeamId() uint32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Team) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

// 战斗环境
type BattleEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atk           *Team                  `protobuf:"bytes,1,opt,name=atk,proto3" json:"atk,omitempty"`                                           // 攻击方队伍
	Def           *Team                  `protobuf:"bytes,2,opt,name=def,proto3" json:"def,omitempty"`                                           // 防守方队伍
	BattleId      uint32                 `protobuf:"varint,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                // 战斗ID
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // 时间戳
	ConfigVersion uint32                 `protobuf:"varint,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // 配置版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEnv) Reset() {
	*x = BattleEnv{}
	mi := &file_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEnv) ProtoMessage() {}

func (x *BattleEnv) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEnv.ProtoReflect.Descriptor instead.
func (*BattleEnv) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{1}
}

func (x *BattleEnv) GetAtk() *Team {
	if x != nil {
		return x.Atk
	}
	return nil
}

func (x *BattleEnv) GetDef() *Team {
	if x != nil {
		return x.Def
	}
	return nil
}

func (x *BattleEnv) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleEnv) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BattleEnv) GetConfigVersion() uint32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// 开始战斗请求
type StartBattle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atk           *Team                  `protobuf:"bytes,1,opt,name=atk,proto3" json:"atk,omitempty"`                            // 攻击方队伍
	Def           *Team                  `protobuf:"bytes,2,opt,name=def,proto3" json:"def,omitempty"`                            // 防守方队伍
	BattleId      uint32                 `protobuf:"varint,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // 战斗ID
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBattle) Reset() {
	*x = StartBattle{}
	mi := &file_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBattle) ProtoMessage() {}

func (x *StartBattle) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBattle.ProtoReflect.Descriptor instead.
func (*StartBattle) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{2}
}

func (x *StartBattle) GetAtk() *Team {
	if x != nil {
		return x.Atk
	}
	return nil
}

func (x *StartBattle) GetDef() *Team {
	if x != nil {
		return x.Def
	}
	return nil
}

func (x *StartBattle) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *StartBattle) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 战斗输入 (通用请求格式)
type BattleInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*BattleInput_Use
	//	*BattleInput_Resume
	//	*BattleInput_Pause
	//	*BattleInput_UserOp
	Input         isBattleInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleInput) Reset() {
	*x = BattleInput{}
	mi := &file_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleInput) ProtoMessage() {}

func (x *BattleInput) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleInput.ProtoReflect.Descriptor instead.
func (*BattleInput) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{3}
}

func (x *BattleInput) GetInput() isBattleInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *BattleInput) GetUse() *BattleUseItem {
	if x != nil {
		if x, ok := x.Input.(*BattleInput_Use); ok {
			return x.Use
		}
	}
	return nil
}

func (x *BattleInput) GetResume() *BattleResume {
	if x != nil {
		if x, ok := x.Input.(*BattleInput_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *BattleInput) GetPause() *BattlePause {
	if x != nil {
		if x, ok := x.Input.(*BattleInput_Pause); ok {
			return x.Pause
		}
	}
	return nil
}

func (x *BattleInput) GetUserOp() *BattleUserOp {
	if x != nil {
		if x, ok := x.Input.(*BattleInput_UserOp); ok {
			return x.UserOp
		}
	}
	return nil
}

type isBattleInput_Input interface {
	isBattleInput_Input()
}

type BattleInput_Use struct {
	Use *BattleUseItem `protobuf:"bytes,1,opt,name=use,proto3,oneof"`
}

type BattleInput_Resume struct {
	Resume *BattleResume `protobuf:"bytes,2,opt,name=resume,proto3,oneof"`
}

type BattleInput_Pause struct {
	Pause *BattlePause `protobuf:"bytes,3,opt,name=pause,proto3,oneof"`
}

type BattleInput_UserOp struct {
	UserOp *BattleUserOp `protobuf:"bytes,4,opt,name=user_op,json=userOp,proto3,oneof"`
}

func (*BattleInput_Use) isBattleInput_Input() {}

func (*BattleInput_Resume) isBattleInput_Input() {}

func (*BattleInput_Pause) isBattleInput_Input() {}

func (*BattleInput_UserOp) isBattleInput_Input() {}

type BattleUserOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharId        int32                  `protobuf:"varint,1,opt,name=char_id,json=charId,proto3" json:"char_id,omitempty"` // 角色ID
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`          // 操作类型 (attack/defend/use_item
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleUserOp) Reset() {
	*x = BattleUserOp{}
	mi := &file_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleUserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleUserOp) ProtoMessage() {}

func (x *BattleUserOp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleUserOp.ProtoReflect.Descriptor instead.
func (*BattleUserOp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{4}
}

func (x *BattleUserOp) GetCharId() int32 {
	if x != nil {
		return x.CharId
	}
	return 0
}

func (x *BattleUserOp) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// 使用道具请求
type BattleUseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []uint32               `protobuf:"varint,1,rep,packed,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"` // 道具ID列表
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // 使用者ID
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                     // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleUseItem) Reset() {
	*x = BattleUseItem{}
	mi := &file_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleUseItem) ProtoMessage() {}

func (x *BattleUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleUseItem.ProtoReflect.Descriptor instead.
func (*BattleUseItem) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{5}
}

func (x *BattleUseItem) GetItemIds() []uint32 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *BattleUseItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BattleUseItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BattleResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResume) Reset() {
	*x = BattleResume{}
	mi := &file_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResume) ProtoMessage() {}

func (x *BattleResume) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResume.ProtoReflect.Descriptor instead.
func (*BattleResume) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{6}
}

type BattlePause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattlePause) Reset() {
	*x = BattlePause{}
	mi := &file_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattlePause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattlePause) ProtoMessage() {}

func (x *BattlePause) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattlePause.ProtoReflect.Descriptor instead.
func (*BattlePause) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{7}
}

type BattleOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*BattleOutput_Result
	//	*BattleOutput_Replay
	Output        isBattleOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleOutput) Reset() {
	*x = BattleOutput{}
	mi := &file_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleOutput) ProtoMessage() {}

func (x *BattleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleOutput.ProtoReflect.Descriptor instead.
func (*BattleOutput) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{8}
}

func (x *BattleOutput) GetOutput() isBattleOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *BattleOutput) GetResult() *BattleResult {
	if x != nil {
		if x, ok := x.Output.(*BattleOutput_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *BattleOutput) GetReplay() *BattleReplay {
	if x != nil {
		if x, ok := x.Output.(*BattleOutput_Replay); ok {
			return x.Replay
		}
	}
	return nil
}

type isBattleOutput_Output interface {
	isBattleOutput_Output()
}

type BattleOutput_Result struct {
	Result *BattleResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"` // 战斗结果
}

type BattleOutput_Replay struct {
	Replay *BattleReplay `protobuf:"bytes,2,opt,name=replay,proto3,oneof"` // 战斗回放
}

func (*BattleOutput_Result) isBattleOutput_Output() {}

func (*BattleOutput_Replay) isBattleOutput_Output() {}

// 战斗结果
type BattleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Winner        uint32                 `protobuf:"varint,1,opt,name=winner,proto3" json:"winner,omitempty"`                              // 胜方队伍ID
	Loser         uint32                 `protobuf:"varint,2,opt,name=loser,proto3" json:"loser,omitempty"`                                // 败方队伍ID
	AtkDamage     int32                  `protobuf:"varint,3,opt,name=atk_damage,json=atkDamage,proto3" json:"atk_damage,omitempty"`       // 攻击方伤害
	DefDamage     int32                  `protobuf:"varint,4,opt,name=def_damage,json=defDamage,proto3" json:"def_damage,omitempty"`       // 防守方伤害
	Kills         []uint32               `protobuf:"varint,5,rep,packed,name=kills,proto3" json:"kills,omitempty"`                         // 击杀列表
	Duration      int64                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`                          // 战斗持续时间(毫秒)
	BattleScore   int32                  `protobuf:"varint,7,opt,name=battle_score,json=battleScore,proto3" json:"battle_score,omitempty"` // 战斗积分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResult) Reset() {
	*x = BattleResult{}
	mi := &file_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResult) ProtoMessage() {}

func (x *BattleResult) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResult.ProtoReflect.Descriptor instead.
func (*BattleResult) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{9}
}

func (x *BattleResult) GetWinner() uint32 {
	if x != nil {
		return x.Winner
	}
	return 0
}

func (x *BattleResult) GetLoser() uint32 {
	if x != nil {
		return x.Loser
	}
	return 0
}

func (x *BattleResult) GetAtkDamage() int32 {
	if x != nil {
		return x.AtkDamage
	}
	return 0
}

func (x *BattleResult) GetDefDamage() int32 {
	if x != nil {
		return x.DefDamage
	}
	return 0
}

func (x *BattleResult) GetKills() []uint32 {
	if x != nil {
		return x.Kills
	}
	return nil
}

func (x *BattleResult) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BattleResult) GetBattleScore() int32 {
	if x != nil {
		return x.BattleScore
	}
	return 0
}

// 战斗状态
type BattleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      uint32                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`    // 战斗ID
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                          // 当前回合
	AtkHealth     int32                  `protobuf:"varint,3,opt,name=atk_health,json=atkHealth,proto3" json:"atk_health,omitempty"` // 攻击方生命值
	DefHealth     int32                  `protobuf:"varint,4,opt,name=def_health,json=defHealth,proto3" json:"def_health,omitempty"` // 防守方生命值
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                           // 战斗状态 (running/paused/finished)
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleStatus) Reset() {
	*x = BattleStatus{}
	mi := &file_battle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleStatus) ProtoMessage() {}

func (x *BattleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleStatus.ProtoReflect.Descriptor instead.
func (*BattleStatus) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{10}
}

func (x *BattleStatus) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleStatus) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *BattleStatus) GetAtkHealth() int32 {
	if x != nil {
		return x.AtkHealth
	}
	return 0
}

func (x *BattleStatus) GetDefHealth() int32 {
	if x != nil {
		return x.DefHealth
	}
	return 0
}

func (x *BattleStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BattleStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 通用响应消息
type BattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`           // 错误码 (0=成功)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // 消息
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`        // 结果数据(序列化的具体消息)
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResponse) Reset() {
	*x = BattleResponse{}
	mi := &file_battle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResponse) ProtoMessage() {}

func (x *BattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResponse.ProtoReflect.Descriptor instead.
func (*BattleResponse) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{11}
}

func (x *BattleResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BattleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BattleResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BattleResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 批量战斗请求
type BatchBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Battles       []*StartBattle         `protobuf:"bytes,1,rep,name=battles,proto3" json:"battles,omitempty"`                // 战斗列表
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"` // 批次ID
	Parallel      int32                  `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"`             // 是否并行处理
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchBattleRequest) Reset() {
	*x = BatchBattleRequest{}
	mi := &file_battle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBattleRequest) ProtoMessage() {}

func (x *BatchBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBattleRequest.ProtoReflect.Descriptor instead.
func (*BatchBattleRequest) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{12}
}

func (x *BatchBattleRequest) GetBattles() []*StartBattle {
	if x != nil {
		return x.Battles
	}
	return nil
}

func (x *BatchBattleRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchBattleRequest) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

// 批量战斗响应
type BatchBattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BattleResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                   // 战斗结果列表
	BatchId       string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`                    // 批次ID
	SuccessCount  int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`    // 成功数
	FailureCount  int32                  `protobuf:"varint,4,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`    // 失败数
	TotalDuration int64                  `protobuf:"varint,5,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"` // 总耗时(毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchBattleResponse) Reset() {
	*x = BatchBattleResponse{}
	mi := &file_battle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBattleResponse) ProtoMessage() {}

func (x *BatchBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBattleResponse.ProtoReflect.Descriptor instead.
func (*BatchBattleResponse) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{13}
}

func (x *BatchBattleResponse) GetResults() []*BattleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchBattleResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchBattleResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchBattleResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *BatchBattleResponse) GetTotalDuration() int64 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

// 战斗事件 (用于回放)
type BattleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                  // 事件时间戳 (毫秒)
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                                  // 事件类型: "attack"|"skill"|"item"|"heal"|"status"|"end"
	PerformerId   uint32                 `protobuf:"varint,3,opt,name=performer_id,json=performerId,proto3" json:"performer_id,omitempty"`                                           // 执行者ID (角色/队伍)
	TargetId      uint32                 `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                                                    // 目标ID
	Value         int32                  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`                                                                          // 事件值 (伤害/治疗/数值)
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外数据 (技能ID、道具ID等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEvent) Reset() {
	*x = BattleEvent{}
	mi := &file_battle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEvent) ProtoMessage() {}

func (x *BattleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEvent.ProtoReflect.Descriptor instead.
func (*BattleEvent) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{14}
}

func (x *BattleEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BattleEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BattleEvent) GetPerformerId() uint32 {
	if x != nil {
		return x.PerformerId
	}
	return 0
}

func (x *BattleEvent) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *BattleEvent) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BattleEvent) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 战斗回放
type BattleReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattleId      uint32                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`    // 战斗ID
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 战斗开始时间戳
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 战斗结束时间戳
	AtkTeam       *Team                  `protobuf:"bytes,4,opt,name=atk_team,json=atkTeam,proto3" json:"atk_team,omitempty"`        // 攻击方队伍
	DefTeam       *Team                  `protobuf:"bytes,5,opt,name=def_team,json=defTeam,proto3" json:"def_team,omitempty"`        // 防守方队伍
	Events        []*BattleEvent         `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`                         // 事件时间线 (按时间戳排序)
	Result        *BattleResult          `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`                         // 最终战斗结果
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`                       // 回放格式版本 (例如 "1.0")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleReplay) Reset() {
	*x = BattleReplay{}
	mi := &file_battle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleReplay) ProtoMessage() {}

func (x *BattleReplay) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleReplay.ProtoReflect.Descriptor instead.
func (*BattleReplay) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{15}
}

func (x *BattleReplay) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleReplay) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *BattleReplay) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *BattleReplay) GetAtkTeam() *Team {
	if x != nil {
		return x.AtkTeam
	}
	return nil
}

func (x *BattleReplay) GetDefTeam() *Team {
	if x != nil {
		return x.DefTeam
	}
	return nil
}

func (x *BattleReplay) GetEvents() []*BattleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *BattleReplay) GetResult() *BattleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BattleReplay) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 战斗进度报告
type ProgressReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BattleId        uint32                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                      // 战斗ID
	ProgressPercent int32                  `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"` // 进度百分比 (0-100)
	CurrentRound    int32                  `protobuf:"varint,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`          // 当前回合
	Status          *BattleStatus          `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                           // 当前战斗状态
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // 时间戳
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProgressReport) Reset() {
	*x = ProgressReport{}
	mi := &file_battle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressReport) ProtoMessage() {}

func (x *ProgressReport) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressReport.ProtoReflect.Descriptor instead.
func (*ProgressReport) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{16}
}

func (x *ProgressReport) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *ProgressReport) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *ProgressReport) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *ProgressReport) GetStatus() *BattleStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ProgressReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 战斗通知 (异步通知，由 C# 回调 Go)
type BattleNotification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timestamp        int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                    // 通知时间戳
	NotificationType NotificationType       `protobuf:"varint,2,opt,name=notification_type,json=notificationType,proto3,enum=battle.NotificationType" json:"notification_type,omitempty"` // 通知类型
	BattleId         uint32                 `protobuf:"varint,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                                                      // 战斗ID
	Payload          []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                                         // 序列化的详细数据 (ProgressReport/BattleEvent/BattleReplay)
	ErrorMessage     string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                           // 错误消息 (仅在 ERROR_OCCURRED 时)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BattleNotification) Reset() {
	*x = BattleNotification{}
	mi := &file_battle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleNotification) ProtoMessage() {}

func (x *BattleNotification) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleNotification.ProtoReflect.Descriptor instead.
func (*BattleNotification) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{17}
}

func (x *BattleNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BattleNotification) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_STATUS_UPDATE
}

func (x *BattleNotification) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleNotification) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BattleNotification) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BattleContext struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BattleId uint32                 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // 战斗ID
	Tick     uint64                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`                         // 当前Tick
	// Types that are valid to be assigned to Option:
	//
	//	*BattleContext_BattleInput
	//	*BattleContext_BattleOutput
	Option        isBattleContext_Option `protobuf_oneof:"option"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleContext) Reset() {
	*x = BattleContext{}
	mi := &file_battle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleContext) ProtoMessage() {}

func (x *BattleContext) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleContext.ProtoReflect.Descriptor instead.
func (*BattleContext) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{18}
}

func (x *BattleContext) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleContext) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *BattleContext) GetOption() isBattleContext_Option {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *BattleContext) GetBattleInput() *BattleInput {
	if x != nil {
		if x, ok := x.Option.(*BattleContext_BattleInput); ok {
			return x.BattleInput
		}
	}
	return nil
}

func (x *BattleContext) GetBattleOutput() *BattleOutput {
	if x != nil {
		if x, ok := x.Option.(*BattleContext_BattleOutput); ok {
			return x.BattleOutput
		}
	}
	return nil
}

type isBattleContext_Option interface {
	isBattleContext_Option()
}

type BattleContext_BattleInput struct {
	BattleInput *BattleInput `protobuf:"bytes,3,opt,name=battle_input,json=battleInput,proto3,oneof"` // 通用战斗输入
}

type BattleContext_BattleOutput struct {
	BattleOutput *BattleOutput `protobuf:"bytes,4,opt,name=battle_output,json=battleOutput,proto3,oneof"` // 开始战斗请求
}

func (*BattleContext_BattleInput) isBattleContext_Option() {}

func (*BattleContext_BattleOutput) isBattleContext_Option() {}

var File_battle_proto protoreflect.FileDescriptor

const file_battle_proto_rawDesc = "" +
	"\n" +
	"\fbattle.proto\x12\x06battle\"T\n" +
	"\x04Team\x12\x16\n" +
	"\x06lineup\x18\x01 \x03(\rR\x06lineup\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\rR\x06teamId\x12\x1b\n" +
	"\tteam_name\x18\x03 \x01(\tR\bteamName\"\xad\x01\n" +
	"\tBattleEnv\x12\x1e\n" +
	"\x03atk\x18\x01 \x01(\v2\f.battle.TeamR\x03atk\x12\x1e\n" +
	"\x03def\x18\x02 \x01(\v2\f.battle.TeamR\x03def\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\rR\bbattleId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0econfig_version\x18\x05 \x01(\rR\rconfigVersion\"\x88\x01\n" +
	"\vStartBattle\x12\x1e\n" +
	"\x03atk\x18\x01 \x01(\v2\f.battle.TeamR\x03atk\x12\x1e\n" +
	"\x03def\x18\x02 \x01(\v2\f.battle.TeamR\x03def\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\rR\bbattleId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xcf\x01\n" +
	"\vBattleInput\x12)\n" +
	"\x03use\x18\x01 \x01(\v2\x15.battle.BattleUseItemH\x00R\x03use\x12.\n" +
	"\x06resume\x18\x02 \x01(\v2\x14.battle.BattleResumeH\x00R\x06resume\x12+\n" +
	"\x05pause\x18\x03 \x01(\v2\x13.battle.BattlePauseH\x00R\x05pause\x12/\n" +
	"\auser_op\x18\x04 \x01(\v2\x14.battle.BattleUserOpH\x00R\x06userOpB\a\n" +
	"\x05input\"E\n" +
	"\fBattleUserOp\x12\x17\n" +
	"\achar_id\x18\x01 \x01(\x05R\x06charId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"_\n" +
	"\rBattleUseItem\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\rR\aitemIds\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x0e\n" +
	"\fBattleResume\"\r\n" +
	"\vBattlePause\"x\n" +
	"\fBattleOutput\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x14.battle.BattleResultH\x00R\x06result\x12.\n" +
	"\x06replay\x18\x02 \x01(\v2\x14.battle.BattleReplayH\x00R\x06replayB\b\n" +
	"\x06output\"\xcf\x01\n" +
	"\fBattleResult\x12\x16\n" +
	"\x06winner\x18\x01 \x01(\rR\x06winner\x12\x14\n" +
	"\x05loser\x18\x02 \x01(\rR\x05loser\x12\x1d\n" +
	"\n" +
	"atk_damage\x18\x03 \x01(\x05R\tatkDamage\x12\x1d\n" +
	"\n" +
	"def_damage\x18\x04 \x01(\x05R\tdefDamage\x12\x14\n" +
	"\x05kills\x18\x05 \x03(\rR\x05kills\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x03R\bduration\x12!\n" +
	"\fbattle_score\x18\a \x01(\x05R\vbattleScore\"\xb3\x01\n" +
	"\fBattleStatus\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\rR\bbattleId\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12\x1d\n" +
	"\n" +
	"atk_health\x18\x03 \x01(\x05R\tatkHealth\x12\x1d\n" +
	"\n" +
	"def_health\x18\x04 \x01(\x05R\tdefHealth\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"t\n" +
	"\x0eBattleResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"z\n" +
	"\x12BatchBattleRequest\x12-\n" +
	"\abattles\x18\x01 \x03(\v2\x13.battle.StartBattleR\abattles\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\x05R\bparallel\"\xd1\x01\n" +
	"\x13BatchBattleResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.battle.BattleResultR\aresults\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x04 \x01(\x05R\ffailureCount\x12%\n" +
	"\x0etotal_duration\x18\x05 \x01(\x03R\rtotalDuration\"\x90\x02\n" +
	"\vBattleEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\fperformer_id\x18\x03 \x01(\rR\vperformerId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\rR\btargetId\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x05R\x05value\x124\n" +
	"\x05extra\x18\x06 \x03(\v2\x1e.battle.BattleEvent.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x02\n" +
	"\fBattleReplay\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\rR\bbattleId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12'\n" +
	"\batk_team\x18\x04 \x01(\v2\f.battle.TeamR\aatkTeam\x12'\n" +
	"\bdef_team\x18\x05 \x01(\v2\f.battle.TeamR\adefTeam\x12+\n" +
	"\x06events\x18\x06 \x03(\v2\x13.battle.BattleEventR\x06events\x12,\n" +
	"\x06result\x18\a \x01(\v2\x14.battle.BattleResultR\x06result\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\"\xc9\x01\n" +
	"\x0eProgressReport\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\rR\bbattleId\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\x05R\x0fprogressPercent\x12#\n" +
	"\rcurrent_round\x18\x03 \x01(\x05R\fcurrentRound\x12,\n" +
	"\x06status\x18\x04 \x01(\v2\x14.battle.BattleStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xd5\x01\n" +
	"\x12BattleNotification\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12E\n" +
	"\x11notification_type\x18\x02 \x01(\x0e2\x18.battle.NotificationTypeR\x10notificationType\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\rR\bbattleId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xc1\x01\n" +
	"\rBattleContext\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\rR\bbattleId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x04R\x04tick\x128\n" +
	"\fbattle_input\x18\x03 \x01(\v2\x13.battle.BattleInputH\x00R\vbattleInput\x12;\n" +
	"\rbattle_output\x18\x04 \x01(\v2\x14.battle.BattleOutputH\x00R\fbattleOutputB\b\n" +
	"\x06option*|\n" +
	"\x14BattleInputOperation\x12\t\n" +
	"\x05Start\x10\x00\x12\r\n" +
	"\tTickEvent\x10\x01\x12\v\n" +
	"\aUseItem\x10\x02\x12\a\n" +
	"\x03End\x10\x03\x12\t\n" +
	"\x05Pause\x10\x04\x12\n" +
	"\n" +
	"\x06Resume\x10\x05\x12\x10\n" +
	"\fStatusUpdate\x10\x06\x12\v\n" +
	"\aDestroy\x10\a*\xc5\x01\n" +
	"\x0fBattleErrorCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x01\x12\x12\n" +
	"\x0eTEAM_NOT_FOUND\x10\x02\x12\x15\n" +
	"\x11INVALID_TEAM_SIZE\x10\x03\x12\x14\n" +
	"\x10BATTLE_NOT_FOUND\x10\x04\x12\x14\n" +
	"\x10DUPLICATE_BATTLE\x10\x05\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x06\x12\v\n" +
	"\aTIMEOUT\x10\a\x12\x18\n" +
	"\x14INVALID_PROTO_FORMAT\x10\b*c\n" +
	"\x10NotificationType\x12\x11\n" +
	"\rSTATUS_UPDATE\x10\x00\x12\x12\n" +
	"\x0eEVENT_OCCURRED\x10\x01\x12\x14\n" +
	"\x10BATTLE_COMPLETED\x10\x02\x12\x12\n" +
	"\x0eERROR_OCCURRED\x10\x03B?Z#goPureWithCsharp/csharp/proto;proto\xaa\x02\x17GoPureWithCsharp.Battleb\x06proto3"

var (
	file_battle_proto_rawDescOnce sync.Once
	file_battle_proto_rawDescData []byte
)

func file_battle_proto_rawDescGZIP() []byte {
	file_battle_proto_rawDescOnce.Do(func() {
		file_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)))
	})
	return file_battle_proto_rawDescData
}

var file_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_battle_proto_goTypes = []any{
	(BattleInputOperation)(0),   // 0: battle.BattleInputOperation
	(BattleErrorCode)(0),        // 1: battle.BattleErrorCode
	(NotificationType)(0),       // 2: battle.NotificationType
	(*Team)(nil),                // 3: battle.Team
	(*BattleEnv)(nil),           // 4: battle.BattleEnv
	(*StartBattle)(nil),         // 5: battle.StartBattle
	(*BattleInput)(nil),         // 6: battle.BattleInput
	(*BattleUserOp)(nil),        // 7: battle.BattleUserOp
	(*BattleUseItem)(nil),       // 8: battle.BattleUseItem
	(*BattleResume)(nil),        // 9: battle.BattleResume
	(*BattlePause)(nil),         // 10: battle.BattlePause
	(*BattleOutput)(nil),        // 11: battle.BattleOutput
	(*BattleResult)(nil),        // 12: battle.BattleResult
	(*BattleStatus)(nil),        // 13: battle.BattleStatus
	(*BattleResponse)(nil),      // 14: battle.BattleResponse
	(*BatchBattleRequest)(nil),  // 15: battle.BatchBattleRequest
	(*BatchBattleResponse)(nil), // 16: battle.BatchBattleResponse
	(*BattleEvent)(nil),         // 17: battle.BattleEvent
	(*BattleReplay)(nil),        // 18: battle.BattleReplay
	(*ProgressReport)(nil),      // 19: battle.ProgressReport
	(*BattleNotification)(nil),  // 20: battle.BattleNotification
	(*BattleContext)(nil),       // 21: battle.BattleContext
	nil,                         // 22: battle.BattleEvent.ExtraEntry
}
var file_battle_proto_depIdxs = []int32{
	3,  // 0: battle.BattleEnv.atk:type_name -> battle.Team
	3,  // 1: battle.BattleEnv.def:type_name -> battle.Team
	3,  // 2: battle.StartBattle.atk:type_name -> battle.Team
	3,  // 3: battle.StartBattle.def:type_name -> battle.Team
	8,  // 4: battle.BattleInput.use:type_name -> battle.BattleUseItem
	9,  // 5: battle.BattleInput.resume:type_name -> battle.BattleResume
	10, // 6: battle.BattleInput.pause:type_name -> battle.BattlePause
	7,  // 7: battle.BattleInput.user_op:type_name -> battle.BattleUserOp
	12, // 8: battle.BattleOutput.result:type_name -> battle.BattleResult
	18, // 9: battle.BattleOutput.replay:type_name -> battle.BattleReplay
	5,  // 10: battle.BatchBattleRequest.battles:type_name -> battle.StartBattle
	12, // 11: battle.BatchBattleResponse.results:type_name -> battle.BattleResult
	22, // 12: battle.BattleEvent.extra:type_name -> battle.BattleEvent.ExtraEntry
	3,  // 13: battle.BattleReplay.atk_team:type_name -> battle.Team
	3,  // 14: battle.BattleReplay.def_team:type_name -> battle.Team
	17, // 15: battle.BattleReplay.events:type_name -> battle.BattleEvent
	12, // 16: battle.BattleReplay.result:type_name -> battle.BattleResult
	13, // 17: battle.ProgressReport.status:type_name -> battle.BattleStatus
	2,  // 18: battle.BattleNotification.notification_type:type_name -> battle.NotificationType
	6,  // 19: battle.BattleContext.battle_input:type_name -> battle.BattleInput
	11, // 20: battle.BattleContext.battle_output:type_name -> battle.BattleOutput
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_battle_proto_init() }
func file_battle_proto_init() {
	if File_battle_proto != nil {
		return
	}
	file_battle_proto_msgTypes[3].OneofWrappers = []any{
		(*BattleInput_Use)(nil),
		(*BattleInput_Resume)(nil),
		(*BattleInput_Pause)(nil),
		(*BattleInput_UserOp)(nil),
	}
	file_battle_proto_msgTypes[8].OneofWrappers = []any{
		(*BattleOutput_Result)(nil),
		(*BattleOutput_Replay)(nil),
	}
	file_battle_proto_msgTypes[18].OneofWrappers = []any{
		(*BattleContext_BattleInput)(nil),
		(*BattleContext_BattleOutput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_battle_proto_goTypes,
		DependencyIndexes: file_battle_proto_depIdxs,
		EnumInfos:         file_battle_proto_enumTypes,
		MessageInfos:      file_battle_proto_msgTypes,
	}.Build()
	File_battle_proto = out.File
	file_battle_proto_goTypes = nil
	file_battle_proto_depIdxs = nil
}
